[tool.poetry]
name = "preprocessing"
version = "0.1.0"
description = "QTIM preprocessing package"
authors = ["Mason Cleveland <mcleveland2@mgh.harvard.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydicom = "^2.4.3"
pandas = "^2.1.3"
visidata = "^2.11.1"
tqdm = "^4.57.0"
bids-validator = "^1.14.0"
pybids = "^0.16.4"
nipype = "^1.8.6"
dicom2nifti = "^2.4.9"
mr-series-selection = {git = "git@github.com:QTIM-Lab/mr-series-selection.git"}
pycrumbs = "^0.2.0"
simpleitk = "^2.3.1"
connected-components-3d = "^3.12.4"
scikit-image = "^0.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
preprocessing = "preprocessing.__main__:main"
