[tool.poetry]
name = "preprocessing"
version = "0.1.0"
description = "QTIM preprocessing package"
authors = ["Mason Cleveland <mcleveland2@mgh.harvard.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydicom = "^2.4.3"
pandas = "^2.1.3"
visidata = "^2.11.1"
tqdm = "^4.57.0"
bids-validator = "^1.14.0"
pybids = "^0.16.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
preprocessing = "preprocessing.__main__:main"
